version = 0.1
[default.deploy.parameters]
stack_name = "llm-router-new2-stack"
resolve_s3 = true
s3_prefix = "llm-router-new2-stack"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
parameter_overrides = "OpenAISecretName=\"OpenAIAPIKey\" AnthropicSecretName=\"AnthropicAPIKey\""
