AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  OpenAISecretName:
    Type: String
    Default: "OpenAIAPIKey"
  AnthropicSecretName:
    Type: String
    Default: "AnthropicAPIKey"
  GoogleSecretName:
    Type: String
    Default: "GeminiAPIKey"

Resources:
  # API Gateway
  LLMApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: LLMRouter
      EndpointConfiguration:
        Types:
          - REGIONAL

  # API Key
  LLMApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      DependsOn:
        - LLMStage
      Name: LLMApiKey
      Enabled: true
      StageKeys:
        - RestApiId: !Ref LLMApi
          StageName: "Prod"

  # Usage Plan
  LLMUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: "LLMProviderUsagePlan"
      ApiStages:
        - ApiId: !Ref LLMApi
          Stage: !Ref LLMStage
      Throttle:
        RateLimit: 10
        BurstLimit: 20
      Quota:
        Limit: 1000
        Period: MONTH

  UsagePlanKey:
    Type: 'AWS::ApiGateway::UsagePlanKey'
    Properties:
      KeyId: !Ref LLMApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref LLMUsagePlan

  # OpenAI Resource
  OpenAIResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref LLMApi
      ParentId: !GetAtt LLMApi.RootResourceId
      PathPart: "openai"

  # Anthropic Resource
  AnthropicResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref LLMApi
      ParentId: !GetAtt LLMApi.RootResourceId
      PathPart: "anthropic"
  
  # Gemini Resource
  GoogleResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref LLMApi
      ParentId: !GetAtt LLMApi.RootResourceId
      PathPart: "google"

  # OpenAI Method
  OpenAIMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref LLMApi
      ResourceId: !Ref OpenAIResource
      HttpMethod: POST
      ApiKeyRequired: True
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: HTTP_PROXY
        Uri: "https://api.openai.com/v1/chat/completions"
        IntegrationResponses:
          - StatusCode: 200
        RequestParameters:
          integration.request.header.Authorization: !Sub "'Bearer {{resolve:secretsmanager:${OpenAISecretName}}}'"
        PassthroughBehavior: WHEN_NO_MATCH

  # Anthropic Method
  AnthropicMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref LLMApi
      ResourceId: !Ref AnthropicResource
      HttpMethod: POST
      ApiKeyRequired: True
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: HTTP_PROXY
        Uri: "https://api.anthropic.com/v1/messages"
        IntegrationResponses:
          - StatusCode: 200
        RequestParameters:
          integration.request.header.Authorization: !Sub "'{{resolve:secretsmanager:${AnthropicSecretName}}}'"
        PassthroughBehavior: WHEN_NO_MATCH

  # Google Method
  GoogleMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref LLMApi
      ResourceId: !Ref GoogleResource
      HttpMethod: POST
      ApiKeyRequired: True
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: HTTP_PROXY
        Uri: "https://generativelanguage.googleapis.com/v1"
        IntegrationResponses:
          - StatusCode: 200
        RequestParameters:
          integration.request.header.Authorization: !Sub "'{{resolve:secretsmanager:${GoogleSecretName}}}'"
        PassthroughBehavior: WHEN_NO_MATCH

  # API Gateway Deployment
  LLMDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref LLMApi
    DependsOn:
      - OpenAIMethod
      - AnthropicMethod
      - GoogleMethod

  # API Gateway Stage with AutoDeploy
  LLMStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref LLMApi
      StageName: "prod"
      DeploymentId: !Ref LLMDeployment
    DependsOn:
      - OpenAIMethod
      - AnthropicMethod
      - GoogleMethod

  # IAM Role for API Gateway to access Secrets Manager
  APIGatewayIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: APIGatewaySecretsRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: APIGatewaySecretsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: 
                  - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${OpenAISecretName}-*"
                  - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${AnthropicSecretName}-*"
                  - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${GoogleSecretName}-*"

Outputs:
  ApiGatewayInvokeURL:
    Description: "API Gateway endpoint"
    Value: !Sub "https://${LLMApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  ApiKey:
    Description: "API Key to access the API Gateway"
    Value: !Ref LLMApiKey
    Export:
      Name: "LLMApiKey"
